<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TripMate Analytics Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        h1 {
            font-size: 22px;
            margin-bottom: 10px;
        }

        h2 {
            font-size: 16px;
            margin-top: 20px;
            margin-bottom: 6px;
        }

        p {
            margin: 2px 0;
        }

        hr {
            margin: 10px 0 15px 0;
        }

        .chart-img {
            width: 100%;
            margin-top: 8px;
            border: 1px solid #ccc;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 6px;
            margin-bottom: 10px;
        }

        table td, table th {
            border: 1px solid #ccc;
            padding: 6px;
            font-size: 12px;
        }

        table th {
            background: #f5f5f5;
        }
    </style>
</head>
<body>

<h1>TripMate Analytics Report</h1>

<p><strong>Generated by:</strong> {{ $adminName }}</p>
<p><strong>Period:</strong> {{ $start }} &rarr; {{ $end }}</p>
<p><strong>Generated At:</strong> {{ $generated }}</p>

<hr>

<h2>Business Joining Rate</h2>
<img src="{{ $charts['businessChart'] }}" class="chart-img" alt="Business Joining Chart">

<h2>Community Content Rate</h2>
<img src="{{ $charts['contentChart'] }}" class="chart-img" alt="Content Rate Chart">

<h2>Member Engagement (Summary)</h2>
<table>
    <tr>
        <th>Metric</th>
        <th>Total</th>
    </tr>
    <tr>
        <td>Likes</td>
        <td>{{ $analytics['engagement']['likes'] ?? 0 }}</td>
    </tr>
    <tr>
        <td>Comments</td>
        <td>{{ $analytics['engagement']['comments'] ?? 0 }}</td>
    </tr>
    <tr>
        <td>Shares</td>
        <td>{{ $analytics['engagement']['shares'] ?? 0 }}</td>
    </tr>
</table>
<img src="{{ $charts['engagementChart'] }}" class="chart-img" alt="Engagement Chart">

<h2>Reported Content (Summary)</h2>
<table>
    <tr>
        <th>Reason</th>
        <th>Total</th>
    </tr>
    <tr>
        <td>Spam</td>
        <td>{{ $analytics['reported']['spam'] ?? 0 }}</td>
    </tr>
    <tr>
        <td>Harassment</td>
        <td>{{ $analytics['reported']['harassment'] ?? 0 }}</td>
    </tr>
    <tr>
        <td>Misinformation</td>
        <td>{{ $analytics['reported']['misinformation'] ?? 0 }}</td>
    </tr>
    <tr>
        <td>Other</td>
        <td>{{ $analytics['reported']['other'] ?? 0 }}</td>
    </tr>
</table>
<img src="{{ $charts['reportedChart'] }}" class="chart-img" alt="Reported Content Chart">

</body>
</html>
